# The Happiness Project - Data Exploration and Cleaning

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

import gmaps
import requests
import json

import statsmodels
import statsmodels.api as sm
from scipy.stats import linregress

### 2021 Happiness Data

In [2]:
# Import World Happiness Report Data 2021
raw_happiness_df = pd.read_csv("Data/world-happiness-report-2021.csv")

# Using DataFrame.insert() to add a column
raw_happiness_df.insert(2, "Year", "2021")

# Rename columns
raw_happiness_df = raw_happiness_df.rename(columns={'Country name': 'Country', 
                                                'Regional indicator': 'Region',
                                                'Ladder score': 'Happiness Score',
                                                'Social support': 'Social Support',                                                    
                                                'Logged GDP per capita': 'GDP per Capita',
                                                'Healthy life expectancy': 'Life Expectancy',
                                                'Freedom to make life choices': 'Freedom',
                                                'Perceptions of corruption': 'Corruption'})

# Drop columns not needed
happiness_df = raw_happiness_df.drop(columns=['Standard error of ladder score', 
                                              'upperwhisker', 
                                              'lowerwhisker',
                                              'Ladder score in Dystopia',
                                              'Explained by: Log GDP per capita',
                                              'Explained by: Social support',
                                              'Explained by: Healthy life expectancy',
                                              'Explained by: Freedom to make life choices',
                                              'Explained by: Generosity',
                                              'Explained by: Perceptions of corruption',
                                              'Dystopia + residual'])

# Write to csv and show preview of DataFrame
happiness_df.to_csv("Data/Final Dataframes/happiness_df.csv", index=False)
happiness_df.head(20)

,Country,Region,Year,Happiness Score,GDP per Capita,Social Support,Life Expectancy,Freedom,Generosity,Corruption
0,Finland,Western Europe,2021,7.842,10.775,0.954,72.000,0.949,-0.098,0.186
1,Denmark,Western Europe,2021,7.620,10.933,0.954,72.700,0.946,0.030,0.179
2,Switzerland,Western Europe,2021,7.571,11.117,0.942,74.400,0.919,0.025,0.292
3,Iceland,Western Europe,2021,7.554,10.878,0.983,73.000,0.955,0.160,0.673
4,Netherlands,Western Europe,2021,7.464,10.932,0.942,72.400,0.913,0.175,0.338
5,Norway,Western Europe,2021,7.392,11.053,0.954,73.300,0.960,0.093,0.270
6,Sweden,Western Europe,2021,7.363,10.867,0.934,72.700,0.945,0.086,0.237
7,Luxembourg,Western Europe,2021,7.324,11.647,0.908,72.600,0.907,-0.034,0.386
8,New Zealand,North America and ANZ,2021,7.277,10.643,0.948,73.400,0.929,0.134,0.242
9,Austria,Western Europe,2021,7.268,10.906,0.934,73.300,0.908,0.042,0.481
10,Australia,North America and ANZ,2021,7.183,10.796,0.940,73.900,0.914,0.159,0.442
11,Israel,Middle East and North Africa,2021,7.157,10.575,0.939,73.503,0.800,0.031,0.753
12,Germany,Western Europe,2021,7.155,10.873,0.903,72.500,0.875,0.011,0.460
13,Canada,North America and ANZ,2021,7.103,10.776,0.926,73.800,0.915,0.089,0.415
14,Ireland,Western Europe,2021,7.085,11.342,0.947,72.400,0.879,0.077,0.363
15,Costa Rica,Latin America and Caribbean,2021,7.069,9.880,0.891,71.400,0.934,-0.126,0.809
16,United Kingdom,Western Europe,2021,7.064,10.707,0.934,72.500,0.859,0.233,0.459
17,Czech Republic,Central and Eastern Europe,2021,6.965,10.556,0.947,70.807,0.858,-0.208,0.868
18,United States,North America and ANZ,2021,6.951,11.023,0.920,68.200,0.837,0.098,0.698
19,Belgium,Western Europe,2021,6.834,10.823,0.906,72.199,0.783,-0.153,0.646

### Historical Happiness Data

In [3]:
# Import World Happiness Report Data 2005-2020
raw_happiness_time = pd.read_csv("Data/world-happiness-report.csv")

# Using DataFrame.insert() to add a column
raw_happiness_time.insert(2, "Region", "")

# Rename columns
raw_happiness_time = raw_happiness_time.rename(columns={'Country name': 'Country',
                                                'year' : 'Year',
                                                'Life Ladder': 'Happiness Score',
                                                'Social support': 'Social Support',  
                                                'Healthy life expectancy at birth': 'Life Expectancy',
                                                'Log GDP per capita': 'GDP per Capita',
                                                'Healthy life expectancy': 'Life Expectancy',
                                                'Freedom to make life choices': 'Freedom',
                                                'Perceptions of corruption': 'Corruption'})

# Drop columns not needed
happiness_time = raw_happiness_time.drop(columns=['Positive affect', 
                                                   'Negative affect' 
                                                  ])
happiness_time

,Country,Year,Region,Happiness Score,GDP per Capita,Social Support,Life Expectancy,Freedom,Generosity,Corruption
0,Afghanistan,2008,,3.724,7.370,0.451,50.80,0.718,0.168,0.882
1,Afghanistan,2009,,4.402,7.540,0.552,51.20,0.679,0.190,0.850
2,Afghanistan,2010,,4.758,7.647,0.539,51.60,0.600,0.121,0.707
3,Afghanistan,2011,,3.832,7.620,0.521,51.92,0.496,0.162,0.731
4,Afghanistan,2012,,3.783,7.705,0.521,52.24,0.531,0.236,0.776
...,...,...,...,...,...,...,...,...,...,...
1944,Zimbabwe,2016,,3.735,7.984,0.768,54.40,0.733,-0.095,0.724
1945,Zimbabwe,2017,,3.638,8.016,0.754,55.00,0.753,-0.098,0.751
1946,Zimbabwe,2018,,3.616,8.049,0.775,55.60,0.763,-0.068,0.844
1947,Zimbabwe,2019,,2.694,7.950,0.759,56.20,0.632,-0.064,0.831
1948,Zimbabwe,2020,,3.160,7.829,0.717,56.80,0.643,-0.009,0.789

In [4]:
# Add data from 2021 to our 2005-2020 DataFrame 
happiness_time_final = pd.concat([happiness_time, happiness_df])

# Convert Year column from string to int
happiness_time_final['Year'] = happiness_time_final['Year'].astype(int)

#  Sort DataFrame by Country and Year for more clarity
happiness_time_final = happiness_time_final.sort_values(['Country', 'Year']).reset_index()

# Add region names
for index, row in happiness_time_final.iterrows():
    
    country =  row['Country']
    if country in happiness_df['Country'].unique():
        row_index = happiness_df.index[happiness_df['Country'] == country][0]
        region = happiness_df.iloc[row_index, 1]
        happiness_time_final.iloc[index, 3] = region

# # # Write to csv and show dataframe preview
happiness_time_final = happiness_time_final.drop("index", axis=1)
happiness_time_final.to_csv("Data/Final Dataframes/happiness_time_final.csv", index=False)
happiness_time_final

,Country,Year,Region,Happiness Score,GDP per Capita,Social Support,Life Expectancy,Freedom,Generosity,Corruption
0,Afghanistan,2008,South Asia,3.724,7.370,0.451,50.800,0.718,0.168,0.882
1,Afghanistan,2009,South Asia,4.402,7.540,0.552,51.200,0.679,0.190,0.850
2,Afghanistan,2010,South Asia,4.758,7.647,0.539,51.600,0.600,0.121,0.707
3,Afghanistan,2011,South Asia,3.832,7.620,0.521,51.920,0.496,0.162,0.731
4,Afghanistan,2012,South Asia,3.783,7.705,0.521,52.240,0.531,0.236,0.776
...,...,...,...,...,...,...,...,...,...,...
2093,Zimbabwe,2017,Sub-Saharan Africa,3.638,8.016,0.754,55.000,0.753,-0.098,0.751
2094,Zimbabwe,2018,Sub-Saharan Africa,3.616,8.049,0.775,55.600,0.763,-0.068,0.844
2095,Zimbabwe,2019,Sub-Saharan Africa,2.694,7.950,0.759,56.200,0.632,-0.064,0.831
2096,Zimbabwe,2020,Sub-Saharan Africa,3.160,7.829,0.717,56.800,0.643,-0.009,0.789
2097,Zimbabwe,2021,Sub-Saharan Africa,3.145,7.943,0.750,56.201,0.677,-0.047,0.821

### Country Data

In [5]:
# COUNTRY DATA

# Load country_data
country_data = pd.read_csv("Data/country_data.csv")

# Rename list for country_data.csv
rename_list = [["Hong Kong", "Hong Kong S.A.R. of China"], 
               ["Taiwan", "Taiwan Province of China", "Taiwan"], 
               ["Congo", "Congo (Brazzaville)", ], 
               ["Macedonia, the former Yugoslav Republic of", "North Macedonia"],  
               ["Palestinian Territory, Occupied", "Palestinian Territories"],
               ["Lao People's Democratic Republic", "Laos"],
               ["Iran, Islamic Republic of", "Iran"],
               ["Tanzania, United Republic of", "Tanzania"],
               ["Moldova, Republic of", "Moldova"]]

# Change the country names to match happiness_df
for item in range (len(rename_list)):
    index = country_data[country_data["Country"] == rename_list[item][0]].index
    country_data.loc[index, 'Country'] = rename_list[item][1]

# Merge with happienss data
country_df = pd.merge(happiness_df[["Country", "Region", "Happiness Score"]], country_data, how='left')

# Add Alpha-2 & 3 codes to happiness df to allow easier merging later on 
happiness_df["Alpha-2 code"] = country_df["Alpha-2 code"]
happiness_df.to_csv("Data/Final Dataframes/happiness_df.csv", index=False)

# Write to csv and display
country_df.to_csv("Data/Final Dataframes/country_df.csv", index=False)
country_df

,Country,Region,Happiness Score,Alpha-2 code,Alpha-3 code,Numeric code,Latitude (average),Longitude (average),Population 2020,Med. Age,Urban Pop %
0,Finland,Western Europe,7.842,FI,FIN,246.0,64.0,26.00,5542237.0,43.0,86%
1,Denmark,Western Europe,7.620,DK,DNK,208.0,56.0,10.00,5795780.0,42.0,88%
2,Switzerland,Western Europe,7.571,CH,CHE,756.0,47.0,8.00,8665615.0,43.0,74%
3,Iceland,Western Europe,7.554,IS,ISL,352.0,65.0,-18.00,341628.0,37.0,94%
4,Netherlands,Western Europe,7.464,NL,NLD,528.0,52.5,5.75,17141544.0,43.0,92%
...,...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,3.512,LS,LSO,426.0,-29.5,28.50,2145194.0,24.0,31%
145,Botswana,Sub-Saharan Africa,3.467,BW,BWA,72.0,-22.0,24.00,2359585.0,24.0,73%
146,Rwanda,Sub-Saharan Africa,3.415,RW,RWA,646.0,-2.0,30.00,13005303.0,20.0,18%
147,Zimbabwe,Sub-Saharan Africa,3.145,ZW,ZWE,716.0,-20.0,30.00,14899771.0,19.0,38%
148,Afghanistan,South Asia,2.523,AF,AFG,4.0,33.0,65.00,39074280.0,18.0,25%

### Weather Data

In [6]:
# Temp and weather data (1991-2016) accessed from World Bank Climate Knowledge Portal
# Availabile at: https://climateknowledgeportal.worldbank.org/download-data
# Sunlight data: World Cities Ranked by Annual Sunshine Hours. Dataset accessed from Kaggle

# TEMPERATURE DATA
# Temp data units = degrees Celsius
temp_data = pd.read_csv("Data/Temp_data.csv")

# Take the mean of each countries monthly average betweeb 1991-2016
temp_data = temp_data.groupby(['ISO3']).mean().reset_index()
# Change column name and drop unneccesary columns
temp_data = temp_data.rename(columns={"Temperature - (Celsius)":"Average Temp"})
temp_data = temp_data.drop(['Year'], axis=1)

# RAINFALL DATA
# Rainfall data units = mm
rainfall_data = pd.read_csv("Data/Rainfall_data.csv")

# Take the mean of each countries monthly average betweeb 1991-2016
rainfall_data = rainfall_data.groupby(['ISO3']).mean().reset_index()
# Change column name and drop unneccesary columns
rainfall_data = rainfall_data.rename(columns={"Rainfall - (MM)":"Average Rainfall"})
rainfall_data = rainfall_data.drop(['Year'], axis=1)

# Merge the temp and rainfall data into weather_data
weather_data = pd.merge(temp_data, rainfall_data, on="ISO3")
weather_data

# SUNLIGHT DATA
# Sunlight data units = annual sunlight hours
sun_data = pd.read_csv("Data/Sunlight_data.csv")
country_data = pd.read_csv("Data/country_data.csv")
sun_data = pd.merge(sun_data, country_data[['Country', "Alpha-3 code"]], on="Country")
sun_data = sun_data.drop(['Country'], axis=1)

# Add sunlight data to weather dataframe
weather_data = pd.merge(weather_data, sun_data, how="left", left_on="ISO3", right_on="Alpha-3 code")
weather_data = weather_data.drop(["Alpha-3 code"], axis=1)
weather_data.drop_duplicates(keep='first', inplace=True)

# Add happiness data
weather_data = pd.merge(country_df[['Country', 'Region', 'Happiness Score', 'Alpha-3 code']],
                        weather_data, how="left", right_on="ISO3", left_on="Alpha-3 code")
weather_data.drop("ISO3", axis=1, inplace=True)

# write to csv and display 
weather_data.reset_index(drop=True)
weather_data.to_csv("Data/Final Dataframes/weather_data.csv", index=False)
weather_data

,Country,Region,Happiness Score,Alpha-3 code,Average Temp,Average Rainfall,Sunlight
0,Finland,Western Europe,7.842,FIN,2.402188,46.890103,1858.000000
1,Denmark,Western Europe,7.620,DNK,8.678213,61.730040,1739.000000
2,Switzerland,Western Europe,7.571,CHE,6.713588,127.114978,1566.000000
3,Iceland,Western Europe,7.554,ISL,2.307253,92.339246,1326.000000
4,Netherlands,Western Europe,7.464,NLD,10.316402,66.786411,1662.000000
...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,3.512,LSO,13.468541,60.716254,NaN
145,Botswana,Sub-Saharan Africa,3.467,BWA,22.295602,31.477969,3426.666667
146,Rwanda,Sub-Saharan Africa,3.415,RWA,20.012486,102.340034,NaN
147,Zimbabwe,Sub-Saharan Africa,3.145,ZWE,22.040161,51.957842,3065.400000
148,Afghanistan,South Asia,2.523,AFG,13.545609,26.843270,3175.100000

### Mental Health Data

In [7]:
# MENTAL HEALTH DATA
# Source: WHO - Depression and Other Common Mental Disorders
# Availabile at: https://www.who.int/publications/i/item/depression-global-health-estimates

# Load data from mental_health.csv and conver rates to percentage
mental_health_data = pd.read_csv("Data/mental_health.csv", encoding='latin1')
mental_health_data['Depression rate'] = mental_health_data['Depression rate'] *100
mental_health_data['Anxiety rate'] = mental_health_data['Anxiety rate'] *100

# Merge with the country data
mental_health_data = pd.merge(happiness_df[['Country', 'Region', 'Happiness Score']], mental_health_data, on="Country", how="left")

# Write to csv and display 
mental_health_data.reset_index(drop=True)
mental_health_data.to_csv("Data/Final Dataframes/mental_health_data.csv", index=False)
mental_health_data

,Country,Region,Happiness Score,Depression rate,Anxiety rate
0,Finland,Western Europe,7.842,5.6,3.2
1,Denmark,Western Europe,7.620,5.0,4.9
2,Switzerland,Western Europe,7.571,5.0,4.9
3,Iceland,Western Europe,7.554,4.1,4.9
4,Netherlands,Western Europe,7.464,4.7,6.4
...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,3.512,4.8,3.1
145,Botswana,Sub-Saharan Africa,3.467,4.7,3.1
146,Rwanda,Sub-Saharan Africa,3.415,3.8,3.2
147,Zimbabwe,Sub-Saharan Africa,3.145,4.0,2.8
148,Afghanistan,South Asia,2.523,3.3,4.0

### COVID Data

In [8]:
# COVID DATA API REQUEST

# Load country_data.csv 
country_data = pd.read_csv("Data/country_data.csv")

# Create a dataframe to store the COVID data
covid_data = pd.DataFrame(columns={"Covid Cases", "Covid Deaths", "Covid Death Rate", "Covid Cases per Mil Pop", "Alpha-2 code"})
covid_data.insert(0, "Country", country_data["Country"])
covid_data
base_url = "http://corona-api.com/countries/"

# Use iterrows to iterate through the dataframe, adding each countires covid data
counter = 0
for index, row in country_data.iterrows():

    try:
        code = row["Alpha-2 code"]
    
        # call the COVID data API
        response = requests.get(base_url + code.lower()).json()
        
        # pull data from response
        covid_cases = response["data"]["latest_data"]["confirmed"]
        covid_deaths = response["data"]["latest_data"]["deaths"]
        covid_death_rate = response["data"]["latest_data"]["calculated"]["death_rate"]
        cases_per_mil_pop = response["data"]["latest_data"]["calculated"]["cases_per_million_population"]
    
        covid_data.loc[index, "Covid Cases"] = float(covid_cases)
        covid_data.loc[index, "Covid Deaths"] = float(covid_deaths)
        covid_data.loc[index, "Covid Cases per Mil Pop"] = float(cases_per_mil_pop)
        covid_data.loc[index, "Alpha-2 code"] = code
        
        if covid_death_rate != None:
            covid_data.loc[index, "Covid Death Rate"] = float(covid_death_rate)
        else:
            covid_data.loc[index, "Covid Death Rate"] = covid_death_rate

        counter += 1
        print(f"{round((counter/len(covid_data)*100),2)}% Done")
    
    except: 
        country = country_data.loc[index, "Country"]
        print(f"Error with country: {country}. No data found")


covid_data.to_csv("Data/covid_data.csv", index=False)
covid_data

0.39% Done
0.78% Done
1.17% Done
1.56% Done
1.95% Done
2.34% Done
2.73% Done
3.12% Done
3.52% Done
3.91% Done
4.3% Done
4.69% Done
5.08% Done
5.47% Done
5.86% Done
6.25% Done
6.64% Done
7.03% Done
7.42% Done
7.81% Done
8.2% Done
8.59% Done
8.98% Done
9.38% Done
9.77% Done
10.16% Done
10.55% Done
10.94% Done
11.33% Done
11.72% Done
12.11% Done
12.5% Done
12.89% Done
13.28% Done
13.67% Done
14.06% Done
14.45% Done
14.84% Done
15.23% Done
15.62% Done
16.02% Done
16.41% Done
16.8% Done
17.19% Done
17.58% Done
17.97% Done
18.36% Done
18.75% Done
19.14% Done
19.53% Done
19.92% Done
20.31% Done
20.7% Done
21.09% Done
21.48% Done
21.88% Done
22.27% Done
22.66% Done
23.05% Done
23.44% Done
23.83% Done
24.22% Done
24.61% Done
25.0% Done
25.39% Done
25.78% Done
26.17% Done
26.56% Done
26.95% Done
27.34% Done
27.73% Done
28.12% Done
28.52% Done
28.91% Done
29.3% Done
29.69% Done
30.08% Done
30.47% Done
30.86% Done
31.25% Done
31.64% Done
32.03% Done
32.42% Done
32.81% Done
33.2% Done
33.59% Done
33.98% Done
34.38% Done
34.77% Done
35.16% Done
35.55% Done
35.94% Done
36.33% Done
36.72% Done
37.11% Done
37.5% Done
37.89% Done
38.28% Done
38.67% Done
39.06% Done
39.45% Done
39.84% Done
40.23% Done
40.62% Done
41.02% Done
41.41% Done
41.8% Done
42.19% Done
42.58% Done
42.97% Done
43.36% Done
43.75% Done
44.14% Done
44.53% Done
44.92% Done
45.31% Done
45.7% Done
46.09% Done
46.48% Done
46.88% Done
47.27% Done
47.66% Done
48.05% Done
48.44% Done
48.83% Done
49.22% Done
49.61% Done
50.0% Done
50.39% Done
50.78% Done
51.17% Done
51.56% Done
51.95% Done
52.34% Done
52.73% Done
53.12% Done
53.52% Done
53.91% Done
54.3% Done
54.69% Done
55.08% Done
55.47% Done
55.86% Done
56.25% Done
56.64% Done
57.03% Done
57.42% Done
57.81% Done
58.2% Done
58.59% Done
58.98% Done
59.38% Done
59.77% Done
60.16% Done
60.55% Done
60.94% Done
Error with country: Namibia. No data found
61.33% Done
61.72% Done
62.11% Done
Error with country: Netherlands Antilles. No data found
62.5% Done
62.89% Done
63.28% Done
63.67% Done
64.06% Done
64.45% Done
64.84% Done
65.23% Done
65.62% Done
66.02% Done
66.41% Done
66.8% Done
67.19% Done
67.58% Done
67.97% Done
68.36% Done
68.75% Done
69.14% Done
69.53% Done
69.92% Done
70.31% Done
70.7% Done
71.09% Done
71.48% Done
71.88% Done
72.27% Done
72.66% Done
73.05% Done
73.44% Done
73.83% Done
74.22% Done
74.61% Done
75.0% Done
75.39% Done
75.78% Done
76.17% Done
76.56% Done
76.95% Done
77.34% Done
77.73% Done
78.12% Done
78.52% Done
78.91% Done
79.3% Done
79.69% Done
80.08% Done
80.47% Done
80.86% Done
81.25% Done
81.64% Done
82.03% Done
82.42% Done
82.81% Done
83.2% Done
83.59% Done
83.98% Done
84.38% Done
84.77% Done
85.16% Done
85.55% Done
85.94% Done
86.33% Done
86.72% Done
87.11% Done
87.5% Done
87.89% Done
88.28% Done
88.67% Done
89.06% Done
89.45% Done
89.84% Done
90.23% Done
90.62% Done
91.02% Done
91.41% Done
91.8% Done
92.19% Done
92.58% Done
92.97% Done
93.36% Done
93.75% Done
94.14% Done
94.53% Done
94.92% Done
95.31% Done
95.7% Done
96.09% Done
96.48% Done
96.88% Done
97.27% Done
97.66% Done
98.05% Done
98.44% Done
98.83% Done
99.22% Done

,Country,Alpha-2 code,Covid Deaths,Covid Cases,Covid Cases per Mil Pop,Covid Death Rate
0,Afghanistan,AF,2625,59745,1124,4.39367
1,Albania,AL,2386,130859,18,1.82334
2,Algeria,DZ,3234,121580,20,2.65998
3,American Samoa,AS,0,0,0,None
4,Andorra,AD,125,13148,24,0.950715
...,...,...,...,...,...,...
251,Wallis and Futuna,WF,7,444,1,1.57658
252,Western Sahara,EH,1,10,0,10
253,Yemen,YE,1216,6263,23,19.4156
254,Zambia,ZM,1249,91484,44,1.36527
255,Zimbabwe,ZW,1565,38191,12,4.09782

In [9]:
# Pull data from covid_data.csv (to save repeating API call)
data = pd.read_csv("Data/covid_data.csv")
final_covid_data = pd.merge(happiness_df[["Country", "Region", "Happiness Score", "Alpha-2 code"]], 
                            data[["Covid Cases", "Covid Deaths", "Covid Death Rate", "Covid Cases per Mil Pop", "Alpha-2 code"]], 
                            how="left", on="Alpha-2 code")

# Drop duplicates
final_covid_data.drop_duplicates(keep='last', inplace=True)

# Write to csv and display
final_covid_data.reset_index(drop=True)
final_covid_data.to_csv("Data/Final Dataframes/final_covid_data.csv", index=False)
final_covid_data

,Country,Region,Happiness Score,Alpha-2 code,Covid Cases,Covid Deaths,Covid Death Rate,Covid Cases per Mil Pop
0,Finland,Western Europe,7.842,FI,86161.0,908.0,1.053841,32.0
1,Denmark,Western Europe,7.620,DK,248950.0,2479.0,0.995782,36.0
2,Switzerland,Western Europe,7.571,CH,653957.0,10587.0,1.618914,237.0
3,Iceland,Western Europe,7.554,IS,6447.0,29.0,0.449822,4.0
4,Netherlands,Western Europe,7.464,NL,1467337.0,17062.0,1.162787,820.0
...,...,...,...,...,...,...,...,...
156,Lesotho,Sub-Saharan Africa,3.512,LS,10728.0,316.0,2.945563,0.0
157,Botswana,Sub-Saharan Africa,3.467,BW,45855.0,691.0,1.506924,1.0
158,Rwanda,Sub-Saharan Africa,3.415,RW,24677.0,330.0,1.337278,6.0
159,Zimbabwe,Sub-Saharan Africa,3.145,ZW,38102.0,1560.0,4.094273,12.0
160,Afghanistan,South Asia,2.523,AF,59370.0,2611.0,4.397844,1124.0

### Combined Data

In [10]:
# Merge country data
final_df = pd.merge(happiness_df, country_df[["Alpha-2 code", "Alpha-3 code", "Numeric code", 
                                              "Latitude (average)", "Longitude (average)", "Population 2020",
                                              "Med. Age", "Urban Pop %"]], how='left', on="Alpha-2 code")


# Merge weather data
final_df = pd.merge(final_df, weather_data[['Alpha-3 code', 'Average Temp', 'Average Rainfall', 'Sunlight']], 
                    on='Alpha-3 code', how="left")

# Merge mental health data
final_df = pd.merge(final_df, mental_health_data[["Country", "Depression rate", "Anxiety rate"]], how="left", on="Country")

# Merge COVID data
final_df = pd.merge(final_df, final_covid_data[["Covid Cases", "Covid Deaths", "Covid Death Rate", "Covid Cases per Mil Pop", "Alpha-2 code"]], how="left", on="Alpha-2 code")

# # Drop duplicates, blanks
final_df.drop_duplicates(keep='last', inplace=True)
final_df.dropna(subset=["Alpha-3 code"], inplace=True)

# # Write to csv
# final_df.reset_index(drop=True)
final_df.to_csv("Data/Final Dataframes/final_df.csv", index=False)
final_df

,Country,Region,Year,Happiness Score,GDP per Capita,Social Support,Life Expectancy,Freedom,Generosity,Corruption,...,Urban Pop %,Average Temp,Average Rainfall,Sunlight,Depression rate,Anxiety rate,Covid Cases,Covid Deaths,Covid Death Rate,Covid Cases per Mil Pop
0,Finland,Western Europe,2021,7.842,10.775,0.954,72.000,0.949,-0.098,0.186,...,86%,2.402188,46.890103,1858.000000,5.6,3.2,86161.0,908.0,1.053841,32.0
1,Denmark,Western Europe,2021,7.620,10.933,0.954,72.700,0.946,0.030,0.179,...,88%,8.678213,61.730040,1739.000000,5.0,4.9,248950.0,2479.0,0.995782,36.0
2,Switzerland,Western Europe,2021,7.571,11.117,0.942,74.400,0.919,0.025,0.292,...,74%,6.713588,127.114978,1566.000000,5.0,4.9,653957.0,10587.0,1.618914,237.0
3,Iceland,Western Europe,2021,7.554,10.878,0.983,73.000,0.955,0.160,0.673,...,94%,2.307253,92.339246,1326.000000,4.1,4.9,6447.0,29.0,0.449822,4.0
4,Netherlands,Western Europe,2021,7.464,10.932,0.942,72.400,0.913,0.175,0.338,...,92%,10.316402,66.786411,1662.000000,4.7,6.4,1467337.0,17062.0,1.162787,820.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,Lesotho,Sub-Saharan Africa,2021,3.512,7.926,0.787,48.700,0.715,-0.131,0.915,...,31%,13.468541,60.716254,NaN,4.8,3.1,10728.0,316.0,2.945563,0.0
187,Botswana,Sub-Saharan Africa,2021,3.467,9.782,0.784,59.269,0.824,-0.246,0.801,...,73%,22.295602,31.477969,3426.666667,4.7,3.1,45855.0,691.0,1.506924,1.0
188,Rwanda,Sub-Saharan Africa,2021,3.415,7.676,0.552,61.400,0.897,0.061,0.167,...,18%,20.012486,102.340034,NaN,3.8,3.2,24677.0,330.0,1.337278,6.0
189,Zimbabwe,Sub-Saharan Africa,2021,3.145,7.943,0.750,56.201,0.677,-0.047,0.821,...,38%,22.040161,51.957842,3065.400000,4.0,2.8,38102.0,1560.0,4.094273,12.0
190,Afghanistan,South Asia,2021,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,...,25%,13.545609,26.843270,3175.100000,3.3,4.0,59370.0,2611.0,4.397844,1124.0

In [11]:
final_df.columns

Index(['Country', 'Region', 'Year', 'Happiness Score', 'GDP per Capita',
       'Social Support', 'Life Expectancy', 'Freedom', 'Generosity',
       'Corruption', 'Alpha-2 code', 'Alpha-3 code', 'Numeric code',
       'Latitude (average)', 'Longitude (average)', 'Population 2020',
       'Med. Age', 'Urban Pop %', 'Average Temp', 'Average Rainfall',
       'Sunlight', 'Depression rate', 'Anxiety rate', 'Covid Cases',
       'Covid Deaths', 'Covid Death Rate', 'Covid Cases per Mil Pop'],
      dtype='object')

### How Happy is Australia?

In [12]:
# Reduce the happiness_time dataframe to just Australia data
australia_happiness = happiness_time_final[happiness_time_final['Country'] == 'Australia']

# Write to csv
australia_happiness.to_csv("Data/Final Dataframes/australia_happiness.csv", index=False)

# Show Australia Happiness dataframe
australia_happiness

,Country,Year,Region,Happiness Score,GDP per Capita,Social Support,Life Expectancy,Freedom,Generosity,Corruption
71,Australia,2005,North America and ANZ,7.341,10.659,0.968,71.40,0.935,NaN,0.390
72,Australia,2007,North America and ANZ,7.285,10.703,0.965,71.72,0.891,0.347,0.513
73,Australia,2008,North America and ANZ,7.254,10.719,0.947,71.88,0.916,0.305,0.431
74,Australia,2010,North America and ANZ,7.450,10.722,0.955,72.20,0.932,0.317,0.366
75,Australia,2011,North America and ANZ,7.406,10.733,0.967,72.30,0.945,0.369,0.382
76,Australia,2012,North America and ANZ,7.196,10.754,0.945,72.40,0.935,0.274,0.368
77,Australia,2013,North America and ANZ,7.364,10.762,0.928,72.50,0.933,0.269,0.432
78,Australia,2014,North America and ANZ,7.289,10.772,0.924,72.60,0.923,0.319,0.442
79,Australia,2015,North America and ANZ,7.309,10.779,0.952,72.70,0.922,0.332,0.357
80,Australia,2016,North America and ANZ,7.250,10.791,0.942,73.00,0.922,0.239,0.399
81,Australia,2017,North America and ANZ,7.257,10.798,0.950,73.30,0.911,0.317,0.411
82,Australia,2018,North America and ANZ,7.177,10.811,0.940,73.60,0.916,0.146,0.405
83,Australia,2019,North America and ANZ,7.234,10.815,0.943,73.90,0.918,0.121,0.430
84,Australia,2020,North America and ANZ,7.137,10.760,0.937,74.20,0.905,0.210,0.491
85,Australia,2021,North America and ANZ,7.183,10.796,0.940,73.90,0.914,0.159,0.442

In [13]:
# Reduce the happiness_time dataframe to just Finland data
finland_happiness = happiness_time_final[happiness_time_final['Country'] == 'Finland']

# Write to csv
finland_happiness.to_csv("Data/Final Dataframes/finland_happiness.csv", index=False)

# Show Finland Happiness dataframe
finland_happiness

,Country,Year,Region,Happiness Score,GDP per Capita,Social Support,Life Expectancy,Freedom,Generosity,Corruption
591,Finland,2006,Western Europe,7.672,10.745,0.965,69.76,0.969,-0.005,0.132
592,Finland,2008,Western Europe,7.671,10.796,0.951,70.08,0.934,0.028,0.217
593,Finland,2010,Western Europe,7.393,10.734,0.935,70.40,0.916,0.091,0.413
594,Finland,2011,Western Europe,7.354,10.754,0.938,70.64,0.936,0.101,0.320
595,Finland,2012,Western Europe,7.420,10.735,0.928,70.88,0.921,-0.001,0.361
596,Finland,2013,Western Europe,7.445,10.722,0.941,71.12,0.919,0.040,0.306
597,Finland,2014,Western Europe,7.385,10.714,0.952,71.36,0.933,-0.001,0.265
598,Finland,2015,Western Europe,7.448,10.716,0.948,71.60,0.930,0.111,0.223
599,Finland,2016,Western Europe,7.660,10.740,0.954,71.70,0.948,-0.027,0.250
600,Finland,2017,Western Europe,7.788,10.768,0.964,71.80,0.962,-0.002,0.192
601,Finland,2018,Western Europe,7.858,10.783,0.962,71.90,0.938,-0.127,0.199
602,Finland,2019,Western Europe,7.780,10.792,0.937,72.00,0.948,-0.052,0.195
603,Finland,2020,Western Europe,7.889,10.750,0.962,72.10,0.962,-0.116,0.164
604,Finland,2021,Western Europe,7.842,10.775,0.954,72.00,0.949,-0.098,0.186

In [14]:
# Reduce the happiness_time dataframe to just Afghanistan data
afghanistan_happiness = happiness_time_final[happiness_time_final['Country'] == 'Afghanistan']

# Write to csv
afghanistan_happiness.to_csv("Data/Final Dataframes/afghanistan_happiness.csv", index=False)

# Show Afghanistan Happiness dataframe
afghanistan_happiness

,Country,Year,Region,Happiness Score,GDP per Capita,Social Support,Life Expectancy,Freedom,Generosity,Corruption
0,Afghanistan,2008,South Asia,3.724,7.370,0.451,50.800,0.718,0.168,0.882
1,Afghanistan,2009,South Asia,4.402,7.540,0.552,51.200,0.679,0.190,0.850
2,Afghanistan,2010,South Asia,4.758,7.647,0.539,51.600,0.600,0.121,0.707
3,Afghanistan,2011,South Asia,3.832,7.620,0.521,51.920,0.496,0.162,0.731
4,Afghanistan,2012,South Asia,3.783,7.705,0.521,52.240,0.531,0.236,0.776
5,Afghanistan,2013,South Asia,3.572,7.725,0.484,52.560,0.578,0.061,0.823
6,Afghanistan,2014,South Asia,3.131,7.718,0.526,52.880,0.509,0.104,0.871
7,Afghanistan,2015,South Asia,3.983,7.702,0.529,53.200,0.389,0.080,0.881
8,Afghanistan,2016,South Asia,4.220,7.697,0.559,53.000,0.523,0.042,0.793
9,Afghanistan,2017,South Asia,2.662,7.697,0.491,52.800,0.427,-0.121,0.954
10,Afghanistan,2018,South Asia,2.694,7.692,0.508,52.600,0.374,-0.094,0.928
11,Afghanistan,2019,South Asia,2.375,7.697,0.420,52.400,0.394,-0.108,0.924
12,Afghanistan,2021,South Asia,2.523,7.695,0.463,52.493,0.382,-0.102,0.924